export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SET_AUTH = 'SET_AUTH';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const LOGOUT = 'LOGOUT';

export const GET_STOCKS = 'GET_STOCKS';
export const GET_STOCKS_SUCCEEDED = 'GET_STOCKS_SUCCEEDED';

export const GET_ERROR = 'GET_ERROR';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const GET_STOCK_HISTORY = 'GET_STOCK_HISTORY';
export const GET_STOCK_HISTORY_SUCCEEDED = 'GET_STOCK_HISTORY_SUCCEEDED';

export const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO';
export const GET_ACCOUNT_INFO_SUCCEEDED = 'GET_ACCOUNT_INFO_SUCCEEDED';
