export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SET_AUTH = 'SET_AUTH';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const LOGOUT = 'LOGOUT';

export const GET_STOCKS = 'GET_STOCKS';
export const GET_STOCKS_SUCCEEDED = 'GET_STOCKS_SUCCEEDED';

export const STOCKS_LOAD_MORE = 'STOCKS_LOAD_MORE';
export const STOCKS_LOAD_MORE_SUCCEEDED = 'STOCK_LOAD_MORE_SUCCEEDED';

export const GET_ERROR = 'GET_ERROR';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const GET_STOCK_HISTORY = 'GET_STOCK_HISTORY';
export const GET_STOCK_HISTORY_SUCCEEDED = 'GET_STOCK_HISTORY_SUCCEEDED';

export const GET_ACCOUNT_INFO = 'GET_ACCOUNT_INFO';
export const GET_ACCOUNT_INFO_SUCCEEDED = 'GET_ACCOUNT_INFO_SUCCEEDED';

export const SELL_STOCKS = 'SELL_STOCKS';
export const SELL_STOCKS_SUCCEEDED = 'SELL_STOCKS_SUCCEEDED';

export const BUY_STOCKS = 'BUY_STOCKS';
export const BUY_STOCKS_SUCCEEDED = 'BUY_STOCKS_SUCCEEDED';

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTIONS_SUCCEEDED = 'GET_TRANSACTION_SUCCEEDED';

export const TRANSACTIONS_LOAD_MORE = 'TRANSACTIONS_LOAD_MORE';
export const TRANSACTIONS_LOAD_MORE_SUCCEEDED = 'TRANSACTION_LOAD_MORE_SUCCEEDED';
